### ISSUE TITLE
error in V2M2

### ISSUE THREAD

**Issue by ZHANG-SHI-CHANG** [zihangJiang/DR-Learning-for-3D-Face#11]
good job for me!
may be some error in V2M2 func, like follow
![image](https://user-images.githubusercontent.com/30692249/64723214-ab2cc680-d502-11e9-88af-52556975be9d.png)
V2M2 generate bad mesh when run generate_mean_face, like follow
![image](https://user-images.githubusercontent.com/30692249/64723507-3dcd6580-d503-11e9-9792-90ee090fe133.png)
i guess new_v + V is need like V2M, V2M is work but also have some bad case, like follow
![image](https://user-images.githubusercontent.com/30692249/64723628-753c1200-d503-11e9-91a8-d82fca814bee.png)
is it normal? can you give me some advice? thx~ a lot!

**Comment by zihangJiang** [comment]
Hi, thanks for your concern and help!
It's abnormal actually and I've fixed it. You can refer to [here](https://github.com/zihangJiang/DR-Learning-for-3D-Face/commit/9a6dbc97207d5d1b81025d843019f1e440a53697#diff-f5de2c5db31367c146a24d7e257f29b5) for detail.
