### ISSUE TITLE
the difference of "train"and "special_train"

### ISSUE THREAD

**Issue by Watebear** [zihangJiang/DR-Learning-for-3D-Face#15]
hi, your work is excellent and i am interested in it. when reading your codes, i can't figure out the difference of the two functions "net.special_train" and "net.train" due to my weak mathematical foundation. could you please tell me why you use the two functions to train your model. thank you very much.

**Comment by zihangJiang** [comment]
Hi, we use net.special_train to train the model to reconstruct the non-emotional face only. The name 'special' might be a little bit confusing, you can just understand it as a warm-up step.
