### ISSUE TITLE
the srcipts for data augmentation

### ISSUE THREAD

**Issue by HgLiJiahao** [zihangJiang/DR-Learning-for-3D-Face#20]
Hi, I've read your paper but I couldn't generate interpolated data by myself :( . Can you release srcipts for data augmentation method metioned in your paper? Thanks very much.

**Comment by zihangJiang** [comment]
Hi, please refer to the code [here](https://github.com/zihangJiang/DR-Learning-for-3D-Face/blob/9a6dbc97207d5d1b81025d843019f1e440a53697/src/data_utils.py#L32).
