### ISSUE TITLE
what is 'delta' in data_utils.py?

### ISSUE THREAD

**Issue by Gogumee** [zihangJiang/DR-Learning-for-3D-Face#6]
First of all, thank you for publishing a great research.

I wonder what Delta means. 

In data_utils.py line 13, delta = np.array([1,0,0,1,0,1,0,0,0])?

Thanks in advance :)

**Comment by QianyiWu** [comment]
Hi, @Gogumee 

This operation was provoked by Eqn(3) in the paper "Alive Caricature from 2D to 3D", where Delta is the identity matrix with zero vector. More specifically, it corresponds to the DR feature of the mean face.

**Comment by Gogumee** [comment]
Hello, @QianyiWu 

Thank you for your Detail explanation.
