### ISSUE TITLE
pretrained model?

### ISSUE THREAD

**Issue by Gogumee** [zihangJiang/DR-Learning-for-3D-Face#7]
Hi!

I think there was a pre-trained model(google drive link). Where did it go?

Thanks in advance :)

ps) Can you tell when an augmentation script will be released?

**Comment by zihangJiang** [comment]
Hi @Gogumee 

We removed the link due to some copyright issue and will add it once confirmed. I'm currently doing my final year project and will clean and update the code when I have time.

**Comment by ghost** [comment]
@zihangJiang any update on this?
