### ISSUE TITLE
Couldn't find face_{}.dat in FacewareHouse Dataset?

### ISSUE THREAD

**Issue by ChenYutongTHU** [zihangJiang/DR-Learning-for-3D-Face#8]
Sorry.
It seems that something named face_{}.dat is needed but I couldn't find it in FaceWareHouse dataset I downloaded. 
Thanks for your help :)

**Comment by zihangJiang** [comment]
Please refer to the script src/get_fwh_Dr.py and section 3.1 in our paper for details.
